### Introducción a la Investigación Operativa y la Optimización

### • Optimización no lineal - Clase 1

**Nazareno Faillace Mullen - Departamento de Matemática, FCEN, UBA**


### Contenidos
* <a href="#whyPython">¿Por qué usar Python?</a>
* <a href ="Sintaxis">Sintaxis</a>
* <a href="#objs">Objetos Básicos de Python</a>
    * <a href="#list">Listas</a>
    * <a href="#tuple">Tupla</a>
* <a href="#Mutables">Mutables e Immutables</a>
* <a href="#tricks">Algunos trucos de Python</a>
* <a href="#func">Funciones</a>
    * <a href="#funcanon">Funciones anónimas</a>
* <a href="#numpy">Librería Numpy</a>
    * <a href="#numpycoms">Comandos útiles para arrays</a>
* <a href="#ders">Derivadas para una función en una variable</a>

<a name="whyPython"></a>
## ¿Por qué usar Python?

![480px-Python-logo-notext.svg.png](attachment:480px-Python-logo-notext.svg.png)

* ¡Gratis!
-  Gran comunidad ($\Rightarrow$ Diversidad de paquetes y funcionalidades)
-  Versátil 
-  Es fácil plasmar ideas 
-  Sintaxis amena

<a name="sintaxis"></a>
## Sintaxis

* Asignar valor: `=`
* Operadores aritméticos: `+, -, *, /, %, **`
   
   En Python son equivalentes, por ejemplo: `x = x + 1` y `x += 1` 

* Operadores de comparación: `==, !=, >, <, >=, <=`
* Operadores de pertenencia: `in, not in`

   Ejemplo:

In [6]:
ls = [1, 2, 9, 11]
print(9 in ls)
print(5 in ls)
print (5 not in ls)

True
False
True


* Loops: `for, while` (indentar el bloque!)
* Condicionales: `if, else, elif` (indentar el bloque!)

<a name="objs"></a>
## Algunos objetos básicos de Python



| Bool | string | set | int | list | dict| float | tuple |   

<a name="list"></a>
### Listas (list)

Uno de los objetos más maleables de Python. Es una colección ordenada de objetos (pueden haber repeticiones). No es necesario que los elementos de una lista sean todos del mismo tipo.

In [7]:
A = [1, 3, 1, 11]
print(A)

[1, 3, 1, 11]


__Importante__: en Python las secuencias (como listas y tuplas) comienzan en el índice 0

Hay varias funciones para las listas que permiten, por ejemplo,  agregar un elemento al final de la lista (`append`) o encontrar el índice de un determinado elemento (`index`). Una lista comprensiva puede encontrarse en este [link](https://www.programiz.com/python-programming/methods/list)


In [8]:
# Definimos una lista
A = [1, 11, 3, -4]
print('A : ', A)

# Agregamos un elemento al final
A.append(17)
print('A : ', A)

# Eliminamos el elemento del índice 2
del A[2]
print('A : ', A)

# Cambiamos el primer elemento
A[0] = 13
print('A : ', A)

# Queremos obtener el una porción de A: desde el índice 1 hasta el final (la lista A no se modifica)
print('A[1:] : ', A[1:])

# Definimos otra lista y las concatenamos (ninguna de las dos listas es modificada)
B = [-1, 8]
print(A + B)

A :  [1, 11, 3, -4]
A :  [1, 11, 3, -4, 17]
A :  [1, 11, -4, 17]
A :  [13, 11, -4, 17]
A[1:] :  [11, -4, 17]
[13, 11, -4, 17, -1, 8]


<a name="tuple"></a>
### Tuplas (tuple)

Las tuplas también son una colección ordenada de objetos (pueden estar repetidos) pero una vez que definimos la tupla, no podemos agregarle ni quitarle elementos. La sintaxis para acceder a sus elementos es igual a la de las listas.

Las tuplas son útiles para cuando sabemos que no realizaremos modificaciones. Además, iterar sobre una tupla es levemente más rápido que iterar sobre una lista.

In [9]:
# Creamos una tupla
A = (1, 5, 3, 7)
print(A)

# Accedemos a su primer elemento
print(A[0])

(1, 5, 3, 7)
1


<a name="Mutables"></a>
##  _mutables_ e _immutables_

Ejercicio:

1. Crear una lista A no vacía
2. Definir una lista `B` que *copie* a `A`, utilizando el comando  `B = A` 
3. Modificar `A` (ej: agregando/quitando/modificando algún elemento)
4. Imprimir `B`

¿Suciedió lo que esperamos? 

In [10]:
A = ["Hola", "Mundo"]
B1 = A #Lo copia por referencia
B2 = (A.copy()) #Lo copia por valor
A[0] = "Chau"
print(B1)
print(B2)

['Chau', 'Mundo']
['Hola', 'Mundo']


Los objetos que vimos anteriormente se dividen en dos categorías: _mutables_ e _immutables_, de la siguiente manera:

__Mutables__: `list`, `set`, `dict`

__Immutables__: `string`, `bool`, `int`, `float`, `tuple`

Un objeto _mutable_ puede cambiar su estado o contenidos, pero un objeto _immutable_ no. En Python, cuando uno asigna un objeto a una variable no está copiando el objeto, sino creando una referencia a él. Para entender la diferencia entre las dos categorías, veremos algunos ejemplos. Utilizaremos el comando `id`

In [11]:
# Definimos dos variables
x = 10
y = x
print('x : ', x)
print('y : ', y)

# Los identificadores de ambas variables apuntan al mismo objeto: 10
print('id(x) == id(y) : ', id(x) == id(y))
print('id(y) == id(10) : ', id(y) == id(10))

x :  10
y :  10
id(x) == id(y) :  True
id(y) == id(10) :  True


Efectuamos una operación que cambia el valor de `x`. Veamos qué ocurre:

In [12]:
# Ahora efectuamos una operación que modifica el valor de x
print('Cambia el valor de x')
x = x + 1

# Los identificadores de ambas variables apuntan distintos objetos
print('id(x) == id(y) : ', id(x) == id(y))
print('id(y) == id(10) : ', id(y) == id(10))

Cambia el valor de x
id(x) == id(y) :  False
id(y) == id(10) :  True


Asignamos un nuevo valor a `x` pero el objeto `10` no cambió. Notar que tampoco cambió el valor de `y` (sigue valiendo `10`)

Veamos qué ocurre con un objeto _mutable_:

In [13]:
# Definimos una lista A
A = [2, 1, 11, -1, 0]
print('A : ', A)
print('id(A) : ', id(A))

# Definimos otra lista B como igual a A
B = A
print('B : ', B)
print('id(B) : ', id(B))

# Los identificadores de A y de B apuntan al mismo objeto: [2, 1, 11, -1, 0]
print('id(A) == id(B) : ', id(A) == id(B))

A :  [2, 1, 11, -1, 0]
id(A) :  140247860062000
B :  [2, 1, 11, -1, 0]
id(B) :  140247860062000
id(A) == id(B) :  True


Veamos qué ocurre si modificamos A:

In [14]:
# Ahora efecutamos una modificación a A: por ejemplo, agregamos un elemento
A.append(99)

# Los identificadores de A y de B siguen apuntando al mismo objeto: [2, 1, 11, -1, 0, 99] 
# Esto ocurre porque, en este caso, el objeto sí cambió
print('A : ', A)
print('id(A) : ', id(A))
print('id(A) == id(B) : ', id(A) == id(B))

A :  [2, 1, 11, -1, 0, 99]
id(A) :  140247860062000
id(A) == id(B) :  True


En este caso, como el objeto lista es _mutable_, el objeto sí cambia. Ahora el objeto es `[2,1,11,-1,0,99]` y las variables `A` y `B` siguen apuntando a él.

__Importante__: si `A` hace referencia a un objeto mutable (como un `set`) y queremos copiar `A` porque, por ejemplo, queremos guardar su estado actual antes de efectuar modificaciones sobre él, debemos recurrir a la función `copy`.

In [15]:
# Definimos A
A = set([2, 1, 11, -1, 0])

# Queremos definir B, una copia de A
B = A.copy()

print('A : ', A)
print('B : ', B)
print('id(A) == id(B) : ', id(A) == id(B))

A :  {0, 1, 2, 11, -1}
B :  {0, 1, 2, 11, -1}
id(A) == id(B) :  False


Notar que tanto `A` como `B` son `set` con los mismos elementos, pero hacen referencia a distintos objetos. Ahora, si efectuamos cambios sobre `A`, `B` no se modifica.

In [16]:
# Eliminamos el elemento más chico de A
A.discard(min(A))

# Agregamos un nuevo elemento a A
A.add(99)

print('A : ', A)
print('B : ', B)

A :  {0, 1, 2, 99, 11}
B :  {0, 1, 2, 11, -1}


Notar que `B` no sufrió cambios.

El comando `deepcopy` se utiliza de igual manera. Es utilizado cuando hay _mutables_ que contienen a otros _mutables_ (como diccionarios que tengan listas como valores). La desventaja de `copy` y, especialmente, de `deepcopy` es que pueden incrementar el tiempo de cómputo significativamente.

__Observación__: si queremos realizar una copia de la lista `A`, basta con escribir `B = A[:]`

<a name="tricks"></a>
## Algunos trucos de Python

### Iteración

En Python generalmente se aprovecha el operador `in` para iterar. Por ejemplo, si deseamos imprimir los números del $2$ al $10$ basta con escribir:

In [17]:
for i in range(2, 11):
    print(i)

2
3
4
5
6
7
8
9
10


`range` tiene la siguiente sintaxis `range(inicio, fin, paso)` donde `fin` no está incluido e `inicio` y `paso`  son opcionales (sus valores por defecto son $0$ y $1$, respectivamente).

Asimismo, con `in` podemos iterar sobre los elementos de cualquier iterable como, por ejemplo, una lista:

In [18]:
L = [-1, 4, 5, 7]

for i in L:
    print(i)

-1
4
5
7


<a name="func"></a>
## Funciones

Declaramos funciones con el comando `def`. El bloque de la función debe estar indentado (al igual que cuando definimos un `while`, `for` o `if`).

Si necesitamos que la función devuelva un valor, usamos el comando `return`.

In [19]:
def cuadrado(n):
    return n**2

x = 4
print(cuadrado(4))

16


Las funciones pueden ser definidas con argumentos opcionales que tienen un valor por defecto.

In [20]:
def potencia(n, m=2):
    return n**m

x = 3

# Si no pasamos el argumento m, la función considera su valor por defecto.
y = potencia(3)
print('potencia(3) : ', y)

# En cambio, si le otorgamos un valor a m:
y = potencia(3,4)
print('potencia(3,4) : ', y)

potencia(3) :  9
potencia(3,4) :  81


__Importante__: las funciones pueden efectuar cambios sobre los objetos _mutables_ . Esto significa que tenemos que prestar atención a los cambios realizados sobre estos objetos, especialmente si los seguiremos utilizando en otras partes del código. 

In [21]:
# La función 'foo' obtiene el último elemento de una lista, 
# lo borra de ella y lo eleva al cuadrado 
def foo(ls):
    y = ls.pop()
    return y**2
    
# Definimos una lista
A = [2, 3 ,7, 11]
print('A : ', A)

# Aplicamos la función
x = foo(A)

# Notar que, aunque Python tenga un scope local en las funciones, 'A' ha sido modificada
print('A después de aplicar la función : ', A)

A :  [2, 3, 7, 11]
A después de aplicar la función :  [2, 3, 7]


 El mismo comportamiento __no__ se observa con los objetos _immutables_

In [22]:
def siguiente(n):
    n += 1
    print('x en la función :', n)
    
# Definimos x
x = 3
print('x antes de la función : ', x)

# Aplicamos la función
siguiente(x)
print('x después de correr la función : ', x)  # El valor de x no cambió fuera de la función

x antes de la función :  3
x en la función : 4
x después de correr la función :  3


In [23]:
# Si queremos que efectivamente x cambie, redefinimos la función de la siguiente manera:
def siguiente(n):
    n += 1
    return n

# Definimos x
x = 3
print('x antes de la función : ', x)

# Aplicamos la función, pero tenemos que asignarle el resultado a x.
x = siguiente(x)
print('x después de asignarle el resultado de la función : ', x) 

x antes de la función :  3
x después de asignarle el resultado de la función :  4


<a name="funcanon"></a>
## Funciones anónimas

El comando `lambda` nos permite definir funciones anónimas (es decir, funciones que no definimos utilizando `def`).

In [24]:
def f(x):
    return 2*x 

g = lambda x: 2*x
print(f(5))
print(g(5))

10
10


Otra de las ventajas que proporcionan es la posibilidad de definir nuevas funciones a partir de otras, pero manteniendo fijos ciertos argumentos. Por ejemplo, en nuestro código definimos la siguiente función:

In [25]:
def pot(base, potencia):
    return base**potencia

Supongamos ahora que en alguna parte del código necesitamos una nueva función que calcule sólo las potencias de $2$. Aquí puede resultar útil declarar una función anónima:

In [26]:
g = lambda x: pot(2,x)

Ahora `g` es una función. Notar que `2` está fijo, entonces `g` calcula $2^x$. Veámoslo:

In [27]:
print(g(2))
print(g(4))
print(g(-1))

4
16
0.5


<a name="numpy"></a>
# Librería Numpy

Utilizaremos los objetos `array` de la librería `numpy` para trabajar con matrices en Python. Es importante notar que un __`array`es mutable__.

La librería numpy se instala con el siguiente comando en la consola:

`pip install numpy`

Al comienzo de nuestro script en Python importamos la librería `numpy` con el alias `np` (para que sea más rápido escribirlo luego):

In [28]:
import numpy as np

Una vez hecho eso, podemos empezar a trabajr con _arrays_. Veamos un par de ejemplos.

Definimos los vectores $v=(0, 1, -1)$ y $w=(2,1, 3)$.

In [29]:
v = np.array([0, 1, -1])
w = np.array([2, 1, 3])

Ahora podemos realizar distintas operaciones.

__Importante:__ **el operador `*` no realiza el producto interno entre dos vectores o el producto entre dos matrices.**  Utilizaremos `*` sólo cuando querramos multiplicar una matriz o un vector por un escalar, ya que `*` realiza multiplicación elemento a elemento. **Para el producto interno entre vectores, el producto entre matrices y el producto entre un vector y una matriz se utiliza el operador `@`**. A continuación, algunos ejemplos.

In [30]:
# Sumamos w y v
z = w+v
print('z = w + v : ',z)

# Realizamos el producto interno entre v y w: z=<v,w>
z = v @ w
print('z = v @ w : ', z)

# Si realizamos operaciones entre vectores y escalares, se interpretan como operaciones lugar a lugar
print(' v + 1 : ', v+1)
print(' w * 2 : ', w*2)

z = w + v :  [2 2 2]
z = v @ w :  -2
 v + 1 :  [1 2 0]
 w * 2 :  [4 2 6]


Las matrices se definen de manera similar a los vectores, sólo que en vez de estar definidas en base a listas, lo están en base a listas de listas. Definimos la siguiente matriz:
$$A =\left( \begin{array}{ccc}
1 & -3 & 2 \\
0 & 6 & -2 \\
4 & 8 & 0 \\
\end{array} \right)
$$

In [31]:
A = np.array([[1, -3, 2], [0, 6, -2], [4, 8 ,0]]) # Notar que cada una de las listas es una fila

También se pueden realizar operaciones entre matrices o entre matrices y vectores, siempre y cuando las dimensiones sean adecuadas. Lo bueno de definir vectores como _arrarys_ es que no tenemos que preocuparnos por trasponerlos si deseamos multiplicarlos por una matriz:

In [32]:
b = A @ v
print(b)

[-5  8  8]


Recordar que $v=(0, 1, -1)$, sin embargo, para efectuar el cálculo $Av^t$, no necesitamos trasponer `v`. 

También podemos acceder a elementos de un _array_. Si se trata de un vector, accedemos a un elemento como lo haríamos si se tratara de una lista, es decir, con `[ ]`.

In [33]:
print('Segunda coordenada de v : ', v[1])
print('Primera coordenada de w : ', w[0])

Segunda coordenada de v :  1
Primera coordenada de w :  2


En el caso de las matrices, la sintaxis es `[fila, columna]`. Por ejemplo, `A[0,1]` es $A_{1 2}$.

Como en el caso de las listas, también podemos utilizar _slices_ para obtener partes de la matriz o vector. Por ejemplo:
* si nos queremos quedar con la primera fila de `A`, lo hacemos de la siguiente manera: `A[0, :]`
* si queremos la submatriz formada por las últimas dos filas y últimas dos columnas: `A[-2:, -2:]`
* si queremos la segunda columna de: `A[:, 1]`

<a name="numpycoms"></a>
### Comandos útiles para arrays

* el atributo `shape` nos devuelve las dimensiones del array: `A.shape` devuelve la tupla `(3, 3)`. Así, si queremos la cantidad de filas de una matriz, usamos `A.shape[0]` y si queremos la cantidad de columnas, `A.shape[1]`. En el caso de los arrays que representan vectores, `shape` devuelve una tupla de un solo elemento, que representa la longitud del vector.

In [34]:
A = np.array([[1, 2, 3], 
              [0, 0, 1]])
np.shape(A)

(2, 3)

* el atributo `T` permite trasponer la matriz. No modifica la matriz original. Por ejemplo, si queremos calcular $A^tA$ basta escribir `A.T @ A`.

In [35]:
A = np.array([[1, 2, 3], 
              [0, 0, 1]])
A.T

array([[1, 0],
       [2, 0],
       [3, 1]])

* el comando `zeros` permite inicializar una matriz o vector nulo (con $0$ en todas sus coordenadas). Hay que pasarle las dimensiones como input. Por ejemplo, `np.zeros((4,3))` devuelve la matriz nula de $4\times 3$ y `np.zeros(A.shape)` devuelve una matriz nula del mismo tamaño que `A`.

In [36]:
N = np.zeros((5,5))
N

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

* el comando `ones` es análogo a `zeros`, sólo que devuelve una matriz con 1 en todas sus filas y columnas.

In [37]:
O = np.ones((3,3))
O

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* el comando `eye` nos permite crear la matriz identidad. Como genera una matriz cuadrada, sólo requiere un entero como input.

In [38]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* el comando `arange` permite generar un vector que contiene a todos los números en un determinado rango. La sintaxis es `np.arange(inicio, fin, paso)` donde `fin`no está incluido y `paso` es optativo (el valor por defecto es 1).

In [39]:
u = np.arange(0,10,2)
u

array([0, 2, 4, 6, 8])

* el comando `random.random` nos permite generar una matriz aleatoria de un determinado tamaño. Toma como input una tupla con el tamaño de la matriz. Por ejemplo, `np.random.random((3,4))` devuelve una matriz de $3\times 4$ y `np.random.random(A.shape)` devuelve una matriz aleatoria con el mismo tamaño que `A`. Los valores aleatorios se encuentran en el intervalo $[0,1)$ 
* recordar que los array son _mutables_. El comando `copy` nos permite crear la copia de un array. Por ejemplo, si queremos crear `B` una copia de `A`, lo hacemos de la siguiente manera: `B = A.copy()`

* el paquete `linalg` de `numpy` tiene algunas funciones que nos serán de utilidad. Por ejemplo, si deseamos importar la función `norm` de `linalg`, que sirve para calcular la norma de un vector o una matriz, escribimos al comienzo del script: `from numpy.linalg import norm` Luego, si queremos calcular la norma de `v`, basta con escribir `norm(v)`

![LaViejaConfiable.jpg](attachment:LaViejaConfiable.jpg)

## Ejercicio

Sean:
$$A = \left( \begin{array}{ccc} 1 & 0 & -1 \\ 2 & 1 & 3 \\ 0 & 1 & -1 \end{array} \right)
\qquad B = \left( \begin{array}{ccc} 0 & -2 & 1 \\ 3 & -1 & 0 \\ 2 & 0 & -1 \end{array} \right)
\qquad v = (-1, 4, -2)$$
Computar en Python la siguiente operación:
$A^tA^2v^t+ BAv^t + <v, A_{1 \cdot}>v^t$ siendo $A_{1 \cdot}$ la primera fila de $A$ 

__Respuesta:__ $(40, 17, 57)$

In [40]:
import numpy as np
from numpy.linalg import norm

In [41]:
A = np.array([[1,0,-1],[2,1,3],[0,1,-1]])
B = np.array([[0,-2,1],[3,-1,0],[2,0,-1]])
v = np.array([-1,4,-2])

res = np.matmul(np.matmul(A.T, A @ A),v.T) + np.matmul(B, A) @ v.T + np.linalg.norm(v @ A[0]) * v.T
res

array([40., 17., 57.])

<a name="ders"></a>
# Derivadas para una función en una variable

### Método forward

Dados $f\in C^2$ y $h>0$, desarrollando Taylor centrado en $x$ tenemos que:
$$f(x+h)=f(x) + f'(x)h + \color{red}{\dfrac{f''(\xi)h^2}{2}} \qquad \xi\in(x,x+h)$$
$$\begin{array}{rll}\Rightarrow f'(x) & = & \dfrac{f(x+h)-f(x)}{h} - \color{red}{\dfrac{f''(\xi)h}{2}} \\ & = & \dfrac{f(x+h)-f(x)}{h} - \color{red}{O(h)} \end{array}$$

Luego, $f'(x)$ puede aproximarse como:
$$f'(x) \approx \dfrac{f(x+h)-f(x)}{h}$$

### Método Backward

Análogo al método forward. Dados $f\in C^2$ y $h>0$, desarrollando Taylor centrado en $x$ tenemos que:
$$f(x-h)=f(x) - f'(x)h + \color{red}{\dfrac{f''(\xi)h^2}{2}} \qquad \xi\in(x-h,x)$$
$$\begin{array}{rll}\Rightarrow f'(x) & = & \dfrac{f(x)-f(x-h)}{h} + \color{red}{\dfrac{f''(\xi)h}{2}} \\ & = & \dfrac{f(x)-f(x-h)}{h} + \color{red}{O(h)} \end{array}$$

Luego, $f'(x)$ puede aproximarse como:
$$f'(x) \approx \dfrac{f(x)-f(x-h)}{h}$$

### Método de centradas

Dados $f\in C^3$ y $h>0$, desarrollando Taylor centrado en $x$ tenemos que:
$$f(x+h)=f(x) + f'(x)h + \dfrac{f''(x)h^2}{2} + \color{red}{\dfrac{f'''(\xi)h^3}{6}} \qquad \xi\in(x,x+h)$$
$$f(x-h)=f(x) - f'(x)h + \dfrac{f''(x)h^2}{2} - \color{red}{\dfrac{f'''(\eta)h^3}{6}} \qquad \eta\in(x-h,x)$$
Restando ambas expresiones, obtenemos que:
$$f(x+h)-f(x-h) = 2f'(x)h+\color{red}{\dfrac{(f'''(\xi)+f'''(\eta))h^3}{6}}$$
$$\begin{array}{rll}\Rightarrow f'(x) & = & \dfrac{f(x+h)-f(x-h)}{2h} + \color{red}{\dfrac{(f'''(\xi)+f'''(\eta))h^2}{12}} \\ & = & \dfrac{f(x+h)-f(x-h)}{2h} + \color{red}{O(h^2)} \end{array}$$

Luego, $f'(x)$ puede aproximarse como:
$$f'(x) \approx \dfrac{f(x+h)-f(x-h)}{2h}$$

## Ejercicio

1. Implementar una función en Python que aproxime la derivada de una función en una variable, para cada uno de los métodos. La función en Python debe tomar como input:
* `f` una función de una variable
* `x` el punto donde se calcula la derivada
* `h` como input opcional, con valor predeterminado de 0.01

2. Para $f(x)=2x^3$, correr alguna de las funciones del punto anterior para aproximar $f'(1)$ para distintos valores de $h$. Comenzar con $h=0.1$ y sucesivamente ir dividiendo el valor de $h$ por $10$ hasta que $h<10^{-20}$. Imprimir en pantalla el resultado para cada valor de $h$. ¿Qué se observa? ¿Por qué sucede?



In [42]:
def derivadaEn1Punto(f, x, h=0.01):
  return((f(x+h)-f(x-h))/(2*h))

In [43]:
der = lambda f,x,h : ((f(x+h)-f(x-h))/(2*h))

In [44]:
f = lambda x: 2*x**3

In [45]:
derivadaEn1Punto(f, 1)

6.000200000000011

In [46]:
xspan = list(np.arange(-10,10,0.01))

In [47]:
import matplotlib.pyplot as plt

In [48]:
ls = [(f, x, 0.01) for x in xspan]
derivada = list(map(lambda t: der(t[0], t[1], t[2]),ls))
evaluacionesoriginal =  list(map(f,xspan))

In [49]:
plt.scatter( xspan, yorigen)
plt.scatter( xspan, yd)
plt.plot()

NameError: ignored

In [ ]:
plt.scatter( xspan, evaluacionesoriginal)
plt.scatter( xspan, derivada)
plt.plot()